# Generated by Django 3.1.6 on 2024-01-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualite', models.CharField(max_length=4)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('suite', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('sexe', models.DateField()),
                ('Telephone', models.CharField(max_length=100)),
                ('admis', models.BooleanField(default=False)),
            ],
        ),
    ]
