# Generated by Django 3.1.6 on 2024-01-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_auto_20240109_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscriptions',
            old_name='Telephone',
            new_name='telephone',
        ),
    ]
