# Generated by Django 3.1.6 on 2024-01-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_auto_20240109_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptions',
            name='id_user',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
