# Generated by Django 3.1.6 on 2024-01-10 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_auto_20240109_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annees',
            fields=[
                ('annee', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Promos',
            fields=[
                ('annee', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nb_inscrit', models.IntegerField()),
                ('nb_recus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('etudiant_promo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('etudiant_qualite', models.CharField(max_length=10)),
                ('etudiant_nom', models.CharField(max_length=100)),
                ('etudiant_prenom', models.CharField(max_length=100)),
                ('etudiant_adresse', models.CharField(max_length=255)),
                ('etudiant_code_postal', models.CharField(max_length=5)),
                ('etudiant_ville', models.CharField(max_length=100)),
                ('etudiant_sexe', models.CharField(max_length=1)),
                ('etudiant_naissance', models.DateField()),
                ('etudiant_num_tel', models.CharField(max_length=20)),
                ('etudiant_mention', models.CharField(blank=True, max_length=50)),
                ('etudiant_annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.promos')),
            ],
        ),
    ]
