# Generated by Django 3.1.6 on 2024-01-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_inscriptions_id_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscriptions',
            options={'verbose_name_plural': 'inscriptions'},
        ),
    ]
