# Generated by Django 3.1.6 on 2024-01-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_etudiants_etudiant_suite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annees',
        ),
        migrations.DeleteModel(
            name='Etudiants',
        ),
        migrations.DeleteModel(
            name='Promos',
        ),
    ]
