# Generated by Django 3.1.6 on 2024-01-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annees',
            fields=[
                ('annee', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entreprises',
            fields=[
                ('n_siret', models.CharField(default='', max_length=14, primary_key=True, serialize=False, unique=True)),
                ('forme_juridique', models.CharField(max_length=10)),
                ('raison_sociale', models.CharField(max_length=200)),
                ('entreprise_adresse', models.CharField(max_length=255)),
                ('entreprise_suite', models.CharField(blank=True, max_length=100)),
                ('entreprise_code_postal', models.CharField(max_length=5)),
                ('entreprise_ville', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=100)),
                ('tel_contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('etudiant_n_promo', models.CharField(max_length=20)),
                ('etudiant_promo', models.CharField(max_length=10)),
                ('etudiant_qualite', models.CharField(max_length=10)),
                ('etudiant_nom', models.CharField(max_length=100)),
                ('etudiant_prenom', models.CharField(max_length=100)),
                ('etudiant_adresse', models.CharField(max_length=255)),
                ('etudiant_suite', models.CharField(blank=True, max_length=255)),
                ('etudiant_code_postal', models.CharField(max_length=5)),
                ('etudiant_ville', models.CharField(max_length=100)),
                ('etudiant_sexe', models.CharField(max_length=1)),
                ('etudiant_naissance', models.DateField()),
                ('etudiant_num_tel', models.CharField(max_length=20)),
                ('etudiant_mention', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professeurs',
            fields=[
                ('prof_numero', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('prof_qualite', models.CharField(max_length=10)),
                ('prof_nom', models.CharField(max_length=100)),
                ('prof_prenom', models.CharField(max_length=100)),
                ('prof_adresse', models.CharField(max_length=255)),
                ('prof_suite', models.CharField(blank=True, max_length=100)),
                ('prof_code_postal', models.CharField(max_length=5)),
                ('prof_ville', models.CharField(max_length=100)),
                ('prof_tel_ecole', models.CharField(max_length=20)),
                ('prof_tel_domicile', models.CharField(blank=True, max_length=20)),
                ('prof_date_embauche', models.DateField()),
                ('prof_date_depart', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promos',
            fields=[
                ('annee', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nb_inscrit', models.IntegerField()),
                ('nb_recus', models.IntegerField()),
                ('prof_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stageform.professeurs')),
            ],
        ),
        migrations.CreateModel(
            name='Tuteurs',
            fields=[
                ('tuteur_numero', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tuteur_entreprise', models.CharField(max_length=20)),
                ('tuteur_qualite', models.CharField(max_length=10)),
                ('tuteur_nom', models.CharField(max_length=100)),
                ('tuteur_prenom', models.CharField(max_length=100)),
                ('tuteur_telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDeStages',
            fields=[
                ('code_type', models.IntegerField(primary_key=True, serialize=False)),
                ('nb_semaines', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('n_stage', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('compte_rendu', models.TextField(blank=True)),
                ('status', models.CharField(max_length=20)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stageform.promos')),
                ('code_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stageform.typedestages')),
                ('etudiant_promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stageform.etudiants')),
                ('prof_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stageform.professeurs')),
                ('siret', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stageform.entreprises')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stageform.tuteurs')),
            ],
        ),
        migrations.AddField(
            model_name='etudiants',
            name='etudiant_annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stageform.promos'),
        ),
        migrations.CreateModel(
            name='effectuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('annee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stageform.annees')),
                ('code_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stageform.typedestages')),
            ],
        ),
        migrations.CreateModel(
            name='Associer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_siret', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stageform.entreprises')),
                ('n_tuteur', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stageform.tuteurs')),
            ],
        ),
        migrations.CreateModel(
            name='Acquerir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niv_exigence', models.IntegerField()),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stageform.competences')),
                ('code_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stageform.typedestages')),
            ],
        ),
    ]
