# Generated by Django 3.1.6 on 2024-01-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageform', '0006_auto_20240111_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeurs',
            name='prof_date_depart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
