# Generated by Django 3.1.6 on 2024-01-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageform', '0007_auto_20240111_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promos',
            name='nb_recus',
            field=models.IntegerField(blank=True),
        ),
    ]
