# Generated by Django 3.1.6 on 2024-01-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageform', '0011_auto_20240111_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiants',
            name='id_user',
            field=models.CharField(default=1, max_length=100, unique=True),
        ),
    ]
