# Generated by Django 3.1.6 on 2024-01-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageform', '0012_auto_20240111_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiants',
            name='id_user',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
