# Generated by Django 3.1.6 on 2024-01-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageform', '0015_etudiants_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promos',
            name='nb_inscrit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='promos',
            name='nb_recus',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
