# Generated by Django 3.1.6 on 2024-01-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageform', '0019_auto_20240112_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stages',
            name='fiche_évaluation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
